// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeHQfAXaTKlLN_BlbiqO7WS32DWoxvick',
    appId: '1:1046937853148:web:5d1d2b113bd23f4d772819',
    messagingSenderId: '1046937853148',
    projectId: 'lifetap-eb5ea',
    authDomain: 'lifetap-eb5ea.firebaseapp.com',
    storageBucket: 'lifetap-eb5ea.firebasestorage.app',
    measurementId: 'G-Q61XE58TLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1gT7IS6h6uT3a1UYVkw3MXvUigoNHeCQ',
    appId: '1:1046937853148:android:f71867608e1d3ba2772819',
    messagingSenderId: '1046937853148',
    projectId: 'lifetap-eb5ea',
    storageBucket: 'lifetap-eb5ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNVe6fABYDwxMx7Vuy41BCbIPtePO38X4',
    appId: '1:1046937853148:ios:b72b0a10c290b27a772819',
    messagingSenderId: '1046937853148',
    projectId: 'lifetap-eb5ea',
    storageBucket: 'lifetap-eb5ea.firebasestorage.app',
    iosBundleId: 'com.lifetap.lifetap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNVe6fABYDwxMx7Vuy41BCbIPtePO38X4',
    appId: '1:1046937853148:ios:b72b0a10c290b27a772819',
    messagingSenderId: '1046937853148',
    projectId: 'lifetap-eb5ea',
    storageBucket: 'lifetap-eb5ea.firebasestorage.app',
    iosBundleId: 'com.lifetap.lifetap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeHQfAXaTKlLN_BlbiqO7WS32DWoxvick',
    appId: '1:1046937853148:web:73f1c44ea933072d772819',
    messagingSenderId: '1046937853148',
    projectId: 'lifetap-eb5ea',
    authDomain: 'lifetap-eb5ea.firebaseapp.com',
    storageBucket: 'lifetap-eb5ea.firebasestorage.app',
    measurementId: 'G-T0MQKM5M49',
  );

}